// ADMIN ACTIONS
export const CHECK_ADMIN_REQUEST = 'CHECK_ADMIN_REQUEST';
export const CHECK_ADMIN_SUCCESS = 'CHECK_ADMIN_SUCCESS';
export const CHECK_ADMIN_FAILURE = 'CHECK_ADMIN_FAILURE';

export const SIGNUP_ADMIN_REQUEST = 'SIGNUP_ADMIN_REQUEST';
export const SIGNUP_ADMIN_SUCCESS = 'SIGNUP_ADMIN_SUCCESS';
export const SIGNUP_ADMIN_FAILURE = 'SIGNUP_ADMIN_FAILURE';

export const LOGIN_ADMIN_REQUEST = 'LOGIN_ADMIN_REQUEST';
export const LOGIN_ADMIN_SUCCESS = 'LOGIN_ADMIN_SUCCESS';
export const LOGIN_ADMIN_FAILURE = 'LOGIN_ADMIN_FAILURE';

export const LOGOUT_ADMIN_REQUEST = 'LOGOUT_ADMIN_REQUEST';
export const LOGOUT_ADMIN_SUCCESS = 'LOGOUT_ADMIN_SUCCESS';
export const LOGOUT_ADMIN_FAILURE = 'LOGOUT_ADMIN_FAILURE';

export const ADD_INITIAL_HOSPITALS_REQUEST = 'ADD_INITIAL_HOSPITALS_REQUEST';
export const ADD_INITIAL_HOSPITALS_SUCCESS = 'ADD_INITIAL_HOSPITALS_SUCCESS';
export const ADD_INITIAL_HOSPITALS_FAILURE = 'ADD_INITIAL_HOSPITALS_FAILURE';


export const ADD_DOCTOR_REQUEST = 'ADD_DOCTOR_REQUEST';
export const ADD_DOCTOR_SUCCESS = 'ADD_DOCTOR_SUCCESS';
export const ADD_DOCTOR_FAILURE = 'ADD_DOCTOR_FAILURE';

export const GET_ALL_DOCTORS_REQUEST = 'GET_ALL_DOCTORS_REQUEST';
export const GET_ALL_DOCTORS_SUCCESS = 'GET_ALL_DOCTORS_SUCCESS';
export const GET_ALL_DOCTORS_FAILURE = 'GET_ALL_DOCTORS_FAILURE';

export const GET_HOSPITALS_REQUEST = 'GET_HOSPITALS_REQUEST';
export const GET_HOSPITALS_SUCCESS = 'GET_HOSPITALS_SUCCESS';
export const GET_HOSPITALS_FAILURE = 'GET_HOSPITALS_FAILURE';

export const ADD_HOSPITAL_REQUEST = 'ADD_HOSPITAL_REQUEST';
export const ADD_HOSPITAL_SUCCESS = 'ADD_HOSPITAL_SUCCESS';
export const ADD_HOSPITAL_FAILURE = 'ADD_HOSPITAL_FAILURE';

export const EDIT_HOSPITAL_REQUEST = 'EDIT_HOSPITAL_REQUEST';
export const EDIT_HOSPITAL_SUCCESS = 'EDIT_HOSPITAL_SUCCESS';
export const EDIT_HOSPITAL_FAILURE = 'EDIT_HOSPITAL_FAILURE';

export const DELETE_HOSPITAL_REQUEST = 'DELETE_HOSPITAL_REQUEST';
export const DELETE_HOSPITAL_SUCCESS = 'DELETE_HOSPITAL_SUCCESS';
export const DELETE_HOSPITAL_FAILURE = 'DELETE_HOSPITAL_FAILURE';

// DOCTOR ACTIONS
export const SIGNUP_DOCTOR_REQUEST = 'SIGNUP_DOCTOR_REQUEST';
export const SIGNUP_DOCTOR_SUCCESS = 'SIGNUP_DOCTOR_SUCCESS';
export const SIGNUP_DOCTOR_FAILURE = 'SIGNUP_DOCTOR_FAILURE';

export const LOGIN_DOCTOR_REQUEST = 'LOGIN_DOCTOR_REQUEST';
export const LOGIN_DOCTOR_SUCCESS = 'LOGIN_DOCTOR_SUCCESS';
export const LOGIN_DOCTOR_FAILURE = 'LOGIN_DOCTOR_FAILURE';

export const LOGOUT_DOCTOR_REQUEST = 'LOGOUT_DOCTOR_REQUEST';
export const LOGOUT_DOCTOR_SUCCESS = 'LOGOUT_DOCTOR_SUCCESS';
export const LOGOUT_DOCTOR_FAILURE = 'LOGOUT_DOCTOR_FAILURE';

export const GET_DOCTOR_HOSPITALS_REQUEST = 'GET_DOCTOR_HOSPITALS_REQUEST';
export const GET_DOCTOR_HOSPITALS_SUCCESS = 'GET_DOCTOR_HOSPITALS_SUCCESS';
export const GET_DOCTOR_HOSPITALS_FAILURE = 'GET_DOCTOR_HOSPITALS_FAILURE';

export const GET_DOCTOR_PATIENTS_REQUEST = 'GET_DOCTOR_PATIENTS_REQUEST';
export const GET_DOCTOR_PATIENTS_SUCCESS = 'GET_DOCTOR_PATIENTS_SUCCESS';
export const GET_DOCTOR_PATIENTS_FAILURE = 'GET_DOCTOR_PATIENTS_FAILURE';

export const SET_CURRENT_PATIENT_REQUEST = 'SET_CURRENT_PATIENT_REQUEST';
export const SET_CURRENT_PATIENT_SUCCESS = 'SET_CURRENT_PATIENT_SUCCESS';
export const SET_CURRENT_PATIENT_FAILURE = 'SET_CURRENT_PATIENT_FAILURE'; 

export const ADD_PATIENT_MEDICAL_CONDITIONS_REQUEST = 'ADD_PATIENT_MEDICAL_CONDITIONS_REQUEST';
export const ADD_PATIENT_MEDICAL_CONDITIONS_SUCCESS = 'ADD_PATIENT_MEDICAL_CONDITIONS_SUCCESS';
export const ADD_PATIENT_MEDICAL_CONDITIONS_FAILURE = 'ADD_PATIENT_MEDICAL_CONDITIONS_FAILURE';

export const EDIT_PATIENT_MEDICAL_CONDITIONS_REQUEST = 'EDIT_PATIENT_MEDICAL_CONDITIONS_REQUEST';
export const EDIT_PATIENT_MEDICAL_CONDITIONS_SUCCESS = 'EDIT_PATIENT_MEDICAL_CONDITIONS_SUCCESS';
export const EDIT_PATIENT_MEDICAL_CONDITIONS_FAILURE = 'EDIT_PATIENT_MEDICAL_CONDITIONS_FAILURE';

export const DELETE_PATIENT_MEDICAL_CONDITIONS_REQUEST = 'DELETE_PATIENT_MEDICAL_CONDITIONS_REQUEST';
export const DELETE_PATIENT_MEDICAL_CONDITIONS_SUCCESS = 'DELETE_PATIENT_MEDICAL_CONDITIONS_SUCCESS';
export const DELETE_PATIENT_MEDICAL_CONDITIONS_FAILURE = 'DELETE_PATIENT_MEDICAL_CONDITIONS_FAILURE';

export const GET_PENDING_REQUEST_PATIENT_REQUEST = 'GET_PENDING_REQUEST_PATIENT_REQUEST';
export const GET_PENDING_REQUEST_PATIENT_SUCCESS = 'GET_PENDING_REQUEST_PATIENT_SUCCESS';
export const GET_PENDING_REQUEST_PATIENT_FAILURE = 'GET_PENDING_REQUEST_PATIENT_FAILURE';

export const MANAGE_PATIENT_REQUEST_REQUEST = 'MANAGE_PATIENT_REQUEST_REQUEST';
export const MANAGE_PATIENT_REQUEST_SUCCESS = 'MANAGE_PATIENT_REQUEST_SUCCESS';
export const MANAGE_PATIENT_REQUEST_FAILURE = 'MANAGE_PATIENT_REQUEST_FAILURE';

export const EDIT_DOCTOR_PROFILE_REQUEST = 'EDIT_DOCTOR_PROFILE_REQUEST';
export const EDIT_DOCTOR_PROFILE_SUCCESS = 'EDIT_DOCTOR_PROFILE_SUCCESS';
export const EDIT_DOCTOR_PROFILE_FAILURE = 'EDIT_DOCTOR_PROFILE_FAILURE';

// PATIENT ACTIONS
export const SIGNUP_PATIENT_REQUEST = 'SIGNUP_PATIENT_REQUEST';
export const SIGNUP_PATIENT_SUCCESS = 'SIGNUP_PATIENT_SUCCESS';
export const SIGNUP_PATIENT_FAILURE = 'SIGNUP_PATIENT_FAILURE';

export const LOGIN_PATIENT_REQUEST = 'LOGIN_PATIENT_REQUEST';
export const LOGIN_PATIENT_SUCCESS = 'LOGIN_PATIENT_SUCCESS';
export const LOGIN_PATIENT_FAILURE = 'LOGIN_PATIENT_FAILURE';

export const LOGOUT_PATIENT_REQUEST = 'LOGOUT_PATIENT_REQUEST';
export const LOGOUT_PATIENT_SUCCESS = 'LOGOUT_PATIENT_SUCCESS';
export const LOGOUT_PATIENT_FAILURE = 'LOGOUT_PATIENT_FAILURE';

export const SET_CURRENT_DOCTOR_REQUEST = 'SET_CURRENT_DOCTOR_REQUEST';
export const SET_CURRENT_DOCTOR_SUCCESS = 'SET_CURRENT_DOCTOR_SUCCESS';
export const SET_CURRENT_DOCTOR_FAILURE = 'SET_CURRENT_DOCTOR_FAILURE'; 

export const SEND_REQUEST_TO_DOCTOR_REQUEST = 'SEND_REQUEST_TO_DOCTOR_REQUEST';
export const SEND_REQUEST_TO_DOCTOR_SUCCESS = 'SEND_REQUEST_TO_DOCTOR_SUCCESS';
export const SEND_REQUEST_TO_DOCTOR_FAILURE = 'SEND_REQUEST_TO_DOCTOR_FAILURE';

export const EDIT_PATIENT_DETAILS_REQUEST = 'EDIT_PATIENT_DETAILS_REQUEST';
export const EDIT_PATIENT_DETAILS_SUCCESS = 'EDIT_PATIENT_DETAILS_SUCCESS';
export const EDIT_PATIENT_DETAILS_FAILURE = 'EDIT_PATIENT_DETAILS_FAILURE';
